# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-05 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='missingparts',
        ),
        migrations.AddField(
            model_name='item',
            name='missingpart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missingparts', to='api.Checkout'),
        ),
        migrations.AlterField(
            model_name='item',
            name='checkedoutto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='api.Checkout'),
        ),
    ]
