# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-08 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200705_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemtypes', to='api.Category'),
        ),
    ]
