# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-08 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200708_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
