# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_checkout_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='createdon',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='partname',
            field=models.CharField(max_length=100),
        ),
    ]
