# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190228_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='applicanttypes',
        ),
        migrations.RemoveField(
            model_name='award',
            name='awardpurposes',
        ),
        migrations.RemoveField(
            model_name='award',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='award',
            name='source',
        ),
        migrations.RemoveField(
            model_name='award',
            name='stemfields',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='areasofinterest',
        ),
        migrations.DeleteModel(
            name='Applicanttype',
        ),
        migrations.DeleteModel(
            name='Areaofinterest',
        ),
        migrations.DeleteModel(
            name='Award',
        ),
        migrations.DeleteModel(
            name='Awardpurpose',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.DeleteModel(
            name='Stemfield',
        ),
    ]
