# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-08 18:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200708_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='phonenumber',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
