# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190314_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
