# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181207_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='checkedoutto',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.Checkout'),
            preserve_default=False,
        ),
    ]
