# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190531_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='fulfilledon',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='returnedon',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
