# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-17 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190617_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='email',
            field=models.CharField(default='test@test.com', max_length=100),
        ),
    ]
