# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-18 17:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_checkout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='test@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(default='402333333', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
